# Generated by Django 3.0.5 on 2020-04-27 18:29

import core.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.CustomManager()),
            ],
        ),
        migrations.CreateModel(
            name='Adicao',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_adicao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField(verbose_name='Quantidade para adicionar')),
                ('destino', models.CharField(max_length=20, verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Adição',
                'verbose_name_plural': 'Adições',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('total', models.FloatField(verbose_name='Total em R$')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Retirar',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_retirada', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField(verbose_name='Quantidade para retirar')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo')),
                ('vem_de_onde', models.CharField(max_length=20, verbose_name='De onde vem')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Retiradas',
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_saldo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Cofre', 'Cofre'), ('Passe', 'Passe'), ('Conta', 'Conta')], max_length=70, verbose_name='Tipo do detalhe')),
                ('quantidade', models.FloatField(verbose_name='Quantidade disponível')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
        migrations.CreateModel(
            name='RegistroRetirada',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Retirar')),
                ('cod_saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Saldo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDespesas',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_registro_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Despesas')),
                ('cod_retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Retirar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAdicao',
            fields=[
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_adicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Adicao')),
                ('cod_saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Saldo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
